name = "loghorizon"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your Supabase transaction connection string here for Cloudflare environment
# DATABASE_URL = "postgres://..."
