BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Content] ALTER COLUMN [description] NVARCHAR(max) NOT NULL;
ALTER TABLE [dbo].[Content] ALTER COLUMN [coverImage] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[Content] ALTER COLUMN [externalUrl] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[Content] ADD [isSuggested] BIT NOT NULL CONSTRAINT [Content_isSuggested_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
